name = 'RS_exc_Rat';
theme = 'sI';
pick = 1;
model = 'HH';
picformat = 'png';
tau_er = 1;
tau_ed = 3;
tau_ir = 1;
tau_id = 5;
paraNoAdap(model,name,theme,tau_er,tau_ed,tau_ir,tau_id);
draw = true;
%draw = false;
%ppp = true;
ppp = false;
npool = 17;
loadData = false;
%loadData = true;
v0 = -0.4:0.1:1.2;
fE = linspace(0.125,0.5,4) * 1e-5;
fE = fE(1:4);
fI = (0.25:0.25:1.0) * 1e-6;
avoidSpike = true;
%v0 = 0.0:0.1:0.2;
noAdapV(theme,name,pick,model,picformat,draw,ppp,loadData,npool,v0,fE,fI,avoidSpike);
